### PR TITLE
Scrape 'last seen' information from profiles

### PR DESCRIPTION
**Pull request by ArtOfCode-**
and return it as a number of seconds since the user was seen.

### CODE REVIEW

**Comment by Undo1** [comment]
@Manishearth Any chance we can get this merged?

Alternatively, if you're too busy in Real Life, Charcoal could take over CE.

**Comment by hichris1234** [comment]
Looks like someone forgot the r? @Manishearth. :)

**Comment by Manishearth** [comment]
Gave you both access, feel free to add more. I'm willing to continue reviewing things though.

**Comment by Undo1** [comment]
Great, thank you! :)

**Pull request merged**
