### PR TITLE
Fix UnicodeDecodeError for is_moderator

### PR DESCRIPTION
**Pull request by ProgramFOX**
Can't say for sure if this works or not so I'll first let the Travis build run

### CODE REVIEW

**Comment by ProgramFOX** [comment]
The build passes. r? @Manishearth (see https://github.com/Manishearth/ChatExchange/pull/128#issuecomment-262627885 for context)

**Comment by hichris1234** [comment]
Travis doesn't run that test on PRs though... I assume that's for security reasons with live testing? Maybe that should be changed? I'm not sure.

**Comment by ProgramFOX** [comment]
It does run tests on PRs: https://travis-ci.org/Manishearth/ChatExchange/builds/178424401

**Comment by hichris1234** [comment]
But compare https://travis-ci.org/Manishearth/ChatExchange/jobs/178424402 to https://travis-ci.org/Manishearth/ChatExchange/jobs/178405641 - only test_browser.py and test_events.py ran for this PR.

**Comment by ProgramFOX** [comment]
Oh, right. I'll see if I can get the test running locally.

**Comment by ProgramFOX** [comment]
So the reason that it didn't run all tests is because it needs the ChatExchangeU and ChatExchangeP environment variables to run everything, and those aren't passed through PRs.

I managed to run test_users.py locally and before this commit it fails, but after, it works.

**Comment by hichris1234** [comment]
The tests are still sad. :( https://travis-ci.org/Manishearth/ChatExchange/builds/178471637

**Comment by ProgramFOX** [comment]
Gasp, this is so much worse. Could you revert this, @hichris1234? Then I'll see if I can find a better solution...

**Comment by Undo1** [comment]
done @ProgramFOX

**Comment by Undo1** [comment]
Well, I tried... Might have done it wrong, though.

**Pull request merged**
