### PR TITLE
Merging ChatExchange6 into ChatExchange

### PR DESCRIPTION
**Pull request by ProgramFOX**
r? @Manishearth 

@ByteCommander I renamed the 'chatexchange6' folder back into 'chatexchange' to make sure that it could still be called 'chatexchange' in the origin repository.

### CODE REVIEW

**Comment by hichris1234** [comment]
Looks like you might need a s/ChatExchange6/ChatExchange.

**Comment by ProgramFOX** [comment]
@hichris1234 Oh right, I forgot that in the examples/ directory. Thanks.

**Comment by ProgramFOX** [comment]
Okay, I got them all now.

**Comment by hichris1234** [comment]
There ended up being some breakage with this; I don't want to make it worse so perhaps someone with actual Python 3 knowledge could help?

**Comment by ProgramFOX** [comment]
@hichris1234 What happened? It should work on both Python 2 and 3 now.

**Comment by hichris1234** [comment]
You can see the matrix from https://travis-ci.org/Manishearth/ChatExchange, apparently 2.6, 2.7, and 3.4 are broken.

**Comment by ProgramFOX** [comment]
It's a UnicodeDecodeError for is_moderator. I'll look into it.

**Comment by hichris1234** [comment]
Actually, strike that, 3.4 worked when I restarted the build so just 2.*.

**Comment by ProgramFOX** [comment]
The build worked on the ChatExchange6 fork though, so it probably depends on a user's username... :/

**Pull request merged**
