### PR TITLE
Added star-cancelling functionality

### PR DESCRIPTION
**Pull request by AbsVolatility**
Added star-cancelling functionality for ROs since it didn't seem to be implemented.

### CODE REVIEW

**Comment by Manishearth** [comment]
@ProgramFOX could you test this?

**Comment by ProgramFOX** [comment]
How would self._client._br.cancel_stars work? I can't find a cancel_stars method in browser.py.

**Comment by ProgramFOX** [comment]
Besides, if you `del self.stars`, why would you do an `if self.stars` later? It's already `del`'d.

**Comment by AbsVolatility** [comment]
@ProgramFOX My apologies, I forgot to update browser.py on GitHub.

I modelled the cancel_stars method on the star and pin methods, which both `del` the relevant value, which I assume will get the program to automatically scrape for the current value.

**Comment by ProgramFOX** [comment]
Ah, right, I forgot the caching that it used.

I'll test this later today.

**Comment by ProgramFOX** [comment]
When I run .cancel_stars(), it crashes because the "method failed to populate attribute", pointing to self.stars. Might not be the best idea to del self.stars. Looks like it would be better to just execute it regardless of whether the message has stars or not.

**Comment by AbsVolatility** [comment]
@ProgramFOX I did some more testing, and it seems to work fine if you use client.get_message to get the message. I think getting the message from messages.Message doesn't work because none of the attributes are initialised, whereas client.get_message does initialise them.

**Comment by ProgramFOX** [comment]
Ah. Then that explains it. But I'd rather have it work using both ways.

**Comment by AbsVolatility** [comment]
@ProgramFOX Well .star() crashes with the same message if you use messages.Message. I've just been making things consistent with the rest of the code.

**Comment by ProgramFOX** [comment]
Oh, I see. I will re-test this later today with that in mind, and see if the .star issue can be fixed.

________________________________

**Comment by ProgramFOX** [comment]
Okay, with that in mind, it works :)

/cc @Manishearth

**Pull request merged**
