### PR TITLE
Don't error on "ok" as response.

### LINKED ISSUE #108: Travis fails
https://travis-ci.org/Manishearth/ChatExchange/builds/72441536

cc @ProgramFOX

### PR DESCRIPTION
**Pull request by ProgramFOX**
This should fix #108.

### CODE REVIEW

**Comment by ProgramFOX** [comment]
Ugh, I'm stupid. This doesn't fix the actual error because it will still enter the "else" statement.

**Comment by ProgramFOX** [comment]
... never mind, I was wrong in my above comment :P

**Comment by Manishearth** [comment]
Travis still failed though.

Can you ensure it doesn't fail locally?

**Comment by ProgramFOX** [comment]
@Manishearth Travis didn't fail anymore after the merge: https://travis-ci.org/Manishearth/ChatExchange

**Comment by Manishearth** [comment]
Oh, it says "1 check failed" above but it's still yellow. *shrug*

**Comment by ProgramFOX** [comment]
Looking at the build errors, it appeared that Travis didn't fetch the PR content well...

**Comment by Manishearth** [comment]
Yeah, but I got an email with green travis, so it's all good now

**Pull request merged**
