### PR TITLE
Build Epydocs to GitLab Pages

### PR DESCRIPTION
**Pull request by jeremyBanks**
*depends on #139*

Builds our Epydocs for every commit on GitLab CI, and publishes to the project's GitLab Pages for every new commit on `master` (or `gl-pages`, intended for development).

As an example [here's the latest build output for my GitLab fork](http://banks.gitlab.io/ChatExchange/epydocs/class-tree.html).

### CODE REVIEW

**Comment by jeremyBanks** [comment]
@Manishearth Thanks for the quick review!

**Comment by Manishearth** [comment]
I noticed you updated the user id -- have you edited this repo's travis vars as well with the creds?

**Comment by jeremyBanks** [comment]
@Manishearth I haven't updated the Travis `secure` variables. I don't think it's necessary to set them in the common Travis configuration file any more. Each user can set them in the Travis settings for their fork instead.

I'll add my current test credentials to the Travis settings for my GitHub fork, so I can also run authenticated tests on Travis from that fork.

(I have also changed my GitHub account from the one which is now @jeremyBanks-archive.)

**Comment by Manishearth** [comment]
I mean, we do want the tests to continue to run for this repo, right?

**Comment by jeremyBanks** [comment]
@Manishearth Yes. Apologies if I was unclear or am confused: as far as I understand it, nothing has changed regarding running tests in this repo. My current understanding of what test will be run:

- in `GitHub/Manishearth/ChatExchange`:
  - Authenticated tests using your test account will run for all commits on `master`, using the credentials specified on line 26 of `travis.yml`.
  - Unauthenticated tests will run for all incoming pull requests.
  - Note that these tests may be flakey due to #141.
- in `GitHub/jeremybanks/ChatExchange`:
  - Authenticated tests using my test account will run for all commits on `master`, using the credentials specified in my Travis CI settings.
  - Unauthenticated tests will run for all incoming pull requests.
- in `GitLab/banks/ChatExchange`:
  - Authenticated tests using my test account will run for all commits, using the credentials specified in my GitLab CI settings.

I don't think that my credentials were ever used in tests for this repository. IIRC they were just committed to the Travis config file because that was the only way to provide to my builds them at the time, but now I can use Travis' settings.

This does still has the problem that authenticated tests aren't necessarily run against pull requests until they're merged, but that seems unavoidable for security reasons, beyond something like manually requiring that contributors include a link to a successful authenticated test run from Travis for their repo.

Note also that my GitLab repo is supposed to mirror `master` from this repository every 24 hours, so it should provide a secondary check (with bonus Epdocs generation) of commits that are merged.

**Pull request merged**
